[runtime]
; use either the test or list sampler.
sampler = list

[list]
filename = ./test_LHS_CAMB.list

[grid]
nsample=10

[output]
save_dir = ./output
filename = ./output/camb_tdata
format = text
verbosity = debug

[pipeline]
modules = consistency camb save_pk
values  = ./y1_mock_values.ini
quiet = True
debug = False
timing = True

[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/camb/camb_interface.py
halofit_version = takahashi
feedback=0
kmax = 50.0
kmin = 5e-3
lmax = 2500
mode=all
power_spectra=delta_tot delta_nonu
nk = 150
nonlinear = both
nz = 50
zmax = 1.0
zmin = 0.0
;sigmar_rmin = 2.
;sigmar_rmax = 70.
;sigma_dr = 0.5

;[mf_tinker]
;file = ${COSMOSIS_STANDARD_LIBRARY}/mass_function/mf_tinker/tinker_mf_module.so
;redshift_zero = 0
;feedback=0
;matter_power_lin_version = 2

;[sigma8_rescale]
;file = ${COSMOSIS_STANDARD_LIBRARY}/utility/sample_sigma8/sigma8_rescale.py

[save_pk]
file = ./scripts/save_pk.py

